### ISSUE TITLE
extension compiles & runs, tests fail

### ISSUE THREAD

**Issue by cdaringe** [asg017/sqlite-html#12]
# problem

```sh
$ make all
# all good, snip snip
```

Extension loads into locally compiled SQLite too! However,

```
$ make test
```

yields test failure on OSX arm:

```
make test-loadable
python3 tests/test-loadable.py
...........ss.......
----------------------------------------------------------------------
Ran 20 tests in 0.002s

OK (skipped=2)
make test-sqlite3
python3 tests/test-sqlite3.py
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x510 pc=0x102b4cd9c]

runtime stack:
runtime.throw({0x102b76036?, 0x0?})
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/panic.go:992 +0x50
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/signal_unix.go:802 +0x1e8

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x102b4d938, 0x1400005ebf8)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/cgocall.go:157 +0x54 fp=0x1400005ebc0 sp=0x1400005eb80 pc=0x102947d84
go.riyazali.net/sqlite._Cfunc__sqlite3_create_function_v2(0x12a604920, 0x6000024200e0, 0x0, 0x801, 0x600002420110, 0x102b4b184, 0x0, 0x0, 0x102b4b448)
	_cgo_gotypes.go:899 +0x3c fp=0x1400005ebf0 sp=0x1400005ebc0 pc=0x102b04c3c
go.riyazali.net/sqlite.(*ExtensionApi).CreateFunction.func2(0x102bf6cc0?, 0x102c2b7f8?, {0x102c2b7f8?, 0x102dfecd0?}, 0x5ed38?, 0x10294ad40?, 0x0?, 0x0?)
	/Users/cdaringe/go/pkg/mod/go.riyazali.net/sqlite@v0.0.0-20211025103955-e79f04eecc1d/func.go:98 +0xd4 fp=0x1400005ec90 sp=0x1400005ebf0 pc=0x102b08b84
go.riyazali.net/sqlite.(*ExtensionApi).CreateFunction(0x14000014480?, {0x102b69ad4?, 0x0?}, {0x102c2b7f8, 0x102dfecd0})
	/Users/cdaringe/go/pkg/mod/go.riyazali.net/sqlite@v0.0.0-20211025103955-e79f04eecc1d/func.go:98 +0xf4 fp=0x1400005ed50 sp=0x1400005ec90 pc=0x102b08624
main.RegisterMeta(0x14000002601?)
	/Users/cdaringe/src/sqlite-html/meta.go:42 +0x40 fp=0x1400005ed90 sp=0x1400005ed50 pc=0x102b49b60
main.Register(0x0?)
	/Users/cdaringe/src/sqlite-html/shared.go:16 +0x24 fp=0x1400005edb0 sp=0x1400005ed90 pc=0x102b4a774
go.riyazali.net/sqlite.go_sqlite3_extension_init(0x12a604920, 0x16d5ca488)
	/Users/cdaringe/go/pkg/mod/go.riyazali.net/sqlite@v0.0.0-20211025103955-e79f04eecc1d/extension.go:21 +0x4c fp=0x1400005ede0 sp=0x1400005edb0 pc=0x102b080cc
_cgoexp_9aaa951c1d34_go_sqlite3_extension_init(0x16d5ca400)
	_cgo_gotypes.go:1541 +0x30 fp=0x1400005ee00 sp=0x1400005ede0 pc=0x102b10e90
runtime.cgocallbackg1(0x102b10e60, 0x0?, 0x0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/cgocall.go:314 +0x248 fp=0x1400005eef0 sp=0x1400005ee00 pc=0x1029481a8
runtime.cgocallbackg(0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/cgocall.go:233 +0xd8 fp=0x1400005ef80 sp=0x1400005eef0 pc=0x102947ed8
runtime.cgocallbackg(0x102b10e60, 0x16d5ca400, 0x0)
	<autogenerated>:1 +0x1c fp=0x1400005efb0 sp=0x1400005ef80 pc=0x1029a78fc
runtime.cgocallback(0x0, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1185 +0xa0 fp=0x1400005efe0 sp=0x1400005efb0 pc=0x1029a5ef0
runtime.goexit()
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 +0x4 fp=0x1400005efe0 sp=0x1400005efe0 pc=0x1029a5fc4
F
======================================================================
FAIL: test_cli_scalar (__main__.TestSqliteHtmlCli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cdaringe/src/sqlite-html/tests/test-sqlite3.py", line 22, in test_cli_scalar
    self.assertEqual(run_sqlite3('select 1;').stdout,  '1\n')
AssertionError: '' != '1\n'
+ 1


----------------------------------------------------------------------
Ran 1 test in 0.022s

FAILED (failures=1)
make[1]: *** [test-sqlite3] Error 1
make: *** [test] Error 2
```

**Comment by asg017** [comment]
`make test` is temporarily broken - I initially tried to also include a statically compiled version of the sqlite3 CLI with sqlite-html builtin (which is what [this part](https://github.com/asg017/sqlite-html/blob/main/Makefile#L54-L62) of the Makefile does). 

But that specifically is broken (throws that nasty segfault). 

`make test` runs both the `test-loadable.py` script, which succeeds, but also runs `test-sqlite3.py` that fails because of the above segfault. 

I should've removed the sqlite3 stuff entirely, but for now, run `make loadable` and `make test-loadable` to avoid all that. 

Glad to see that works on macos arm, though!
